rm *TblAdmins.csv
rm *TblDocuments.csv
rm *TblEventDocuments.csv
rm *TblHrefCategories.csv
rm *TblHrefCategoryCategories.csv
rm *TblHrefs.csv
rm *TblJokes.csv
rm *TblMemberDocuments.csv
rm *TblSuperAdmins.csv
rm *TblSuperAdminsNickNames.csv
rm *vw_displayableMembers.csv
rm *vw_displayablePhotoIDs.csv
rm *vw_siteEventPhotosGroupedAndOrd.csv
rm *vw_siteEventPhotosHighestRanke1.csv
rm *vw_siteEventPhotosHighestRanked.csv
rm *vw_siteEventPhotosOrderedByRan1.csv
rm *vw_siteEventPhotosOrderedByRank.csv
rm *vw_siteMemberPhotosGroupedAndOr.csv
rm *vw_siteMemberPhotosHighestRank1.csv
rm *vw_siteMemberPhotosHighestRanke.csv
rm *vw_siteMemberPhotosOrderedByRa1.csv
rm *vw_siteMemberPhotosOrderedByRan.csv

